#!/bin/bash

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "filename", "value": "/home/filip/Dropbox/ClojureProjects/imp-rest/resources/WNV_small.trees"}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "coordinateName", "value": "location"}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "burnin", "value": "1"}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "nslices", "value": "10"}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "mrsd", "value": "2015.3"}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X GET http://localhost:8080/settings

echo -e '\n'
