#!/bin/bash

#curl -X PUT -H "Content-Type: application/json" \
#    -d '{"id": "trees", "value": "/home/filip/Dropbox/ClojureProjects/imp-rest/resources/WNV_small.trees"}' \
#    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id" : "attribute", "value" : "location"}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "burnin", "value": 1}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "nslices", "value": 10}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "mrsd", "value": 2015.3}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X GET http://localhost:8080/settings

echo -e '\n'

curl -X GET http://localhost:8080/data

echo -e '\n'
