#!/bin/bash

# upload file content
curl -i -X PUT -H "Content-Type: application/json" \
    -d '{"input": "@/home/filip/Dropbox/ClojureProjects/imp-rest/resources/WNV_small.trees"}' \
    http://localhost:8080/trees

echo -e '\n'


# server should respond with attributes and ntrees:
curl -X GET http://localhost:8080/attributes

echo -e '\n'

curl -X GET http://localhost:8080/ntrees

echo -e '\n'


# put settings
curl -X PUT -H "Content-Type: application/json" \
    -d '{"id" : "attribute", "value" : "location"}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "burnin", "value": 1}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "nslices", "value": 10}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X PUT -H "Content-Type: application/json" \
    -d '{"id": "mrsd", "value": 2015.3}' \
    http://localhost:8080/settings

echo -e '\n'

curl -X GET http://localhost:8080/settings

echo -e '\n'

# chew it and get results
curl -X GET http://localhost:8080/results

